#!/usr/bin/env sh
export HUSKY=0

echo "Starting pre-commit hook..."

echo "Formateando código con Prettier en la carpeta src..."
npm run format:src

echo "Ejecutando linting en archivos modificados..."
npx lint-staged

echo "Pre-commit hook completed!"