#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Formateando código con Prettier en la carpeta src..."
npm run format:src

echo "Ejecutando linting en archivos modificados..."
npx lint-staged

# Opcionalmente puedes agregar más verificaciones