#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if [ $? -ne 0 ]; then
  echo "El formato del código no es correcto. Push cancelado."
  exit 1
fi

echo "Todas las verificaciones pasaron. Realizando push..."
exit 0